# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "Manage Credits"
uid = "95f84866-8152-420e-9f29-0eab80d4944e"
handle = "credit-manager"
description = "Credit notes manager - v1.1.2 - CDN cache bust 2025-10-03T16:52:00Z"

# Controls where in POS your extension will be injected,
# and the file that contains your extensionâ€™s source code.
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
